version: "3.9"  

services:
  api:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - ./backends:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: brainzcode-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=brainzcode_auth
      - POSTGRES_PASSWORD=brainzcode_auth
      - POSTGRES_DB=airbnb_auth
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: brainzcode-pgadmin
    depends_on:
        - db
    ports:
        - "5052:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: contact@brainzcode.com
        PGADMIN_DEFAULT_PASSWORD: brainzcode
    restart: always

volumes:
  postgres_data:



